---
all:
  hosts:
    sonar-01:
      ansible_host: <host>
    nexus-01:
      ansible_host: <host>
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: <user>